// HeartWise Seed Data Generator
// Run this to inject 200 Q&As into the app

const QA = [
// === EDUCATION (40) ===
{c:'education',r:'student',q:'What are the highest-yield resources for Step 2 CK if I want to go into cardiology?',a:'First Aid Step 2 CK and UWorld are non-negotiable. For cardiology-specific prep, read the ACC/AHA guidelines for the big conditions. Amboss is excellent for quick reference. Your clinical rotations will teach you more than any book.'},
{c:'education',r:'resident',q:'How important is the cardiology in-training exam (ITE) for fellowship applications?',a:'Very important. Programs use it as an objective measure. Aim above 70th percentile. Study with ACCSAP. Some programs have cutoffs. A strong ITE score combined with good letters is a powerful combination.'},
{c:'education',r:'fellow',q:'What resources do you recommend for interventional cardiology boards?',a:'SCAI board review materials, Kern\u2019s Cardiac Catheterization Handbook, and SCAI consensus statements on PCI and complications. Do as many practice questions as you can find. Heavy on hemodynamics, complications management, and procedural decision-making. Peripheral intervention questions are increasing.'},
{c:'education',r:'student',q:'Is it worth doing a research year between MS3 and MS4 if I want cardiology?',a:'Depends on your application. If you have minimal research, a dedicated year can boost your CV. But it\u2019s not required. If you do one, make sure you\u2019ll get first-author publications \u2014 not just data collection. A productive year with 2-3 publications is worth it. A year of data collection for someone else\u2019s paper is not.'},
{c:'education',r:'resident',q:'What\u2019s the best way to learn ECG interpretation beyond the basics?',a:'Start with Dubin\u2019s, then Goldberger. The real learning happens by reading every ECG on service. For advanced stuff \u2014 Brugada, WPW, fascicular blocks \u2014 Life in the Fast Lane is excellent. Read 5 ECGs a day and within a year you\u2019ll be better than most attendings.'},
{c:'education',r:'student',q:'Should I do an away rotation in cardiology as an MS4?',a:'Away rotations matter more for surgical subspecialties. For cardiology fellowship, you apply from residency. Focus on getting the best IM residency you can. That\u2019s the path to cardiology.'},
{c:'education',r:'fellow',q:'How do I get better at reading coronary angiograms?',a:'Takes hundreds of cases. Learn coronary anatomy cold in every view. Watch every case in the cath lab. Use ACC angiographic training modules. Review your own cases after the fact. Within 6 months you\u2019ll see dramatic improvement.'},
{c:'education',r:'resident',q:'Is ACCSAP worth the money for cardiology fellowship prep?',a:'Yes, 100%. It\u2019s the closest thing to the actual board exam. Many programs provide it free. If not, split the cost with co-fellows. Single best investment for cardiology boards.'},
{c:'education',r:'student',q:'What cardiology electives should I prioritize during medical school?',a:'General cardiology consult rotation first. Then a cath lab elective to see if you like procedures. Echo rotation is also high-yield. The consult rotation is king.'},
{c:'education',r:'fellow',q:'How should I prepare for complex PCI cases as a first-year interventional fellow?',a:'Before every case, review the prior angiogram, know the anatomy, have plans A, B, and C. Read SCAI expert consensus on complex PCI. For CTOs study the hybrid algorithm. Watch TCT and EuroPCR case reviews on YouTube. Assist on as many complex cases as possible.'},
{c:'education',r:'resident',q:'What journals should I be reading regularly?',a:'JACC, Circulation, and European Heart Journal. Follow them on Twitter for highlights. NEJM for landmark trials. Read one landmark cardiology trial per week and know the details.'},
{c:'education',r:'student',q:'How do I decide between cardiology and cardiothoracic surgery?',a:'Very different paths. CT surgery is 7+ years with brutal hours. Cardiology is IM + 3-year fellowship + 1 for interventional. IC is increasingly doing what surgeons used to \u2014 TAVR, MitraClip, structural interventions. Shadow both extensively. The daily life is very different.'},
{c:'education',r:'fellow',q:'Tips for learning transesophageal echo during fellowship?',a:'Get your hands on the probe as much as possible. Volunteer for every TEE case. ASE has excellent online training modules. Practice the standard 28-view comprehensive exam until it\u2019s muscle memory. Learn to drive the probe yourself from day one.'},
{c:'education',r:'resident',q:'Should I pursue an MBA alongside cardiology training?',a:'MBA is practical for practice management and leadership roles. Many programs offer executive MBAs compatible with fellowship. A PhD only makes sense for dedicated academic research careers. Don\u2019t do either just for credentials. Have a clear plan.'},
{c:'education',r:'student',q:'What\u2019s the most underrated topic in cardiology that students should learn early?',a:'Heart failure management. Most common reason for hospitalization over 65. If you understand HFrEF management and GDMT optimization cold, you\u2019ll impress every cardiology attending you work with.'},
{c:'education',r:'fellow',q:'What conferences should interventional fellows attend?',a:'TCT (Transcatheter Cardiovascular Therapeutics) is the most important for IC. Also CRT (Cardiovascular Research Technologies), ACC Scientific Sessions, and EuroPCR for European data. Submit abstracts to present \u2014 it looks great on your CV and forces you to learn deeply.'},
{c:'education',r:'resident',q:'How do I build a strong research portfolio for fellowship applications?',a:'Start early in PGY-2. Find a cardiology mentor who publishes regularly. Case reports are the easiest entry point. Then move to retrospective studies using existing databases. Aim for 2-3 first-author publications by application time. Quality over quantity \u2014 one JACC paper beats five in low-impact journals.'},
{c:'education',r:'student',q:'Is there a difference between DO and MD applicants for cardiology fellowship?',a:'Historically there was bias, but it\u2019s decreasing. DO applicants match cardiology fellowship regularly now. What matters is your residency training, letters, research, and board scores. If you\u2019re at a strong IM program with good mentorship, your degree letters matter less than your performance.'},
{c:'education',r:'fellow',q:'How much simulation training should I do before live CTO cases?',a:'As much as possible. Many programs have sim labs with coronary models. SCAI offers CTO workshops with hands-on simulation. The Hybrid CTO course is excellent. Practice wire manipulation, microcatheter exchanges, and retrograde techniques. When you get to your first live case, the fundamentals should be muscle memory.'},
{c:'education',r:'resident',q:'What\u2019s the best way to present at cardiology grand rounds?',a:'Pick a topic your attendings care about. Use real cases to anchor the teaching points. Keep it to 30-40 minutes. Know the landmark trials relevant to your topic. Anticipate questions. Practice at least twice. Make it interactive \u2014 ask the audience their approach before revealing the data. Attendings remember residents who present well.'},
{c:'education',r:'student',q:'How early should I start thinking about cardiology as a career?',a:'You don\u2019t need to decide until PGY-2 at the earliest. During med school, focus on being the best IM student you can be. Do a cardiology elective to test your interest. If you love it, make sure you match at a strong IM program with good cardiology fellowship placement. You don\u2019t need to commit until you\u2019re actually ready to apply.'},
{c:'education',r:'fellow',q:'Should I learn IVUS or OCT first?',a:'IVUS first. It\u2019s used more widely and most attendings will expect you to interpret it. Learn to identify the vessel wall layers, plaque morphology, and stent apposition. Once you\u2019re comfortable with IVUS, OCT is relatively intuitive \u2014 it\u2019s higher resolution but has a narrower field of view. Know the strengths and limitations of each. IVUS for left main sizing, OCT for stent optimization and thin-cap fibroatheroma.'},
{c:'education',r:'resident',q:'What\u2019s the value of getting ECMO certified as a cardiology fellow?',a:'Huge value. Mechanical circulatory support is a rapidly growing field. If you can manage ECMO, Impella, and balloon pumps, you\u2019re significantly more marketable. Many programs now expect this. Take the ELSO certification course. Get comfortable with cannulation, circuit management, and weaning protocols. This skill set will define the next generation of cardiologists.'},

// === CLINICAL (40) ===
{c:'clinical',r:'resident',q:'How do you approach new-onset atrial fibrillation in a hospitalized patient?',a:'Rate control first \u2014 IV metoprolol or diltiazem. Find the trigger: infection, PE, thyroid, post-surgical, alcohol. Calculate CHA2DS2-VASc for stroke risk. If \u22652 in men or \u22653 in women, start anticoagulation (DOACs preferred). Don\u2019t rush rhythm control unless hemodynamically unstable.'},
{c:'clinical',r:'student',q:'When should you suspect cardiac tamponade?',a:'Beck\u2019s triad: hypotension, muffled heart sounds, JVD \u2014 but only present in ~30% of cases. Key clues: pulsus paradoxus >10mmHg, electrical alternans on ECG, plethoric IVC on echo. Get stat echo. Treatment is pericardiocentesis. True emergency \u2014 don\u2019t wait for formal echo if crashing.'},
{c:'clinical',r:'fellow',q:'How do you decide between DES and DCB for in-stent restenosis?',a:'DCB is my first choice for focal ISR in a well-expanded stent. Avoids adding more metal. But for complex ISR (long segment, recoil, dissection), DES is often better. Always optimize with high-pressure NC balloon first before deciding.'},
{c:'clinical',r:'resident',q:'How do you manage a STEMI patient arriving more than 12 hours after symptom onset?',a:'If ongoing ischemia (persistent ST elevation, chest pain, hemodynamic instability) \u2014 cath lab regardless of timing. If stable and pain-free at 12+ hours, data suggests routine PCI of totally occluded artery doesn\u2019t help. Medical management and reassess. Clinical judgment matters more than arbitrary time cutoffs.'},
{c:'clinical',r:'student',q:'How do you differentiate STEMI from benign early repolarization?',a:'BER: concave upward ST (smiley face), V2-V5, normal QTc. STEMI: convex or straight ST (frowny face), vascular distribution, reciprocal changes, evolves over time. When in doubt, repeat ECG in 15-20 minutes. Serial troponins help. Never feel bad about activating the cath lab if unsure.'},
{c:'clinical',r:'fellow',q:'What\u2019s your wire escalation strategy for CTO PCI?',a:'Start with workhorse wire (Sion, Fielder XT). Escalate to polymer-jacketed (Fielder FC, Pilot 200). Harder caps: Confianza Pro 12 or Gaia series. If antegrade fails, consider dissection-reentry or retrograde. The hybrid algorithm should guide strategy based on cap, length, collaterals, and morphology.'},
{c:'clinical',r:'resident',q:'When do you use milrinone vs dobutamine in acute heart failure?',a:'Dobutamine is first-line for low output. Milrinone is better with significant pulmonary hypertension. Milrinone causes more hypotension and has a longer half-life. For patients on chronic beta-blockers, milrinone may work better. Renally dose milrinone. Always consider whether they need mechanical support instead.'},
{c:'clinical',r:'student',q:'Explain systolic vs diastolic heart failure simply?',a:'Systolic (HFrEF): heart is weak, can\u2019t pump enough blood out. EF <40%. Four pillars of therapy. Diastolic (HFpEF): heart is stiff, can\u2019t relax to fill. EF \u226550%. Treatment is mostly diuretics, SGLT2i, and managing comorbidities. This distinction matters enormously for management.'},
{c:'clinical',r:'fellow',q:'How do you manage a coronary perforation in the cath lab?',a:'Stay calm. Inflate balloon at perforation to tamponade. Get echo for pericardial effusion. Small wire perforation: prolonged balloon inflation. Large perforation: covered stent. Reverse anticoagulation with protamine. Pericardiocentesis ready if tamponade develops. CT surgery aware. Most are manageable if you act quickly.'},
{c:'clinical',r:'resident',q:'What\u2019s the difference between NSTEMI and unstable angina?',a:'The difference is troponin. With high-sensitivity assays, almost every ACS now has detectable troponin. True UA is increasingly rare. Management is the same: anticoagulation, DAPT, risk stratification, early invasive strategy for high-risk. Focus on TIMI or GRACE score, not the label.'},
{c:'clinical',r:'student',q:'What complications should I watch for after cardiac catheterization?',a:'Access site: hematoma, pseudoaneurysm, retroperitoneal bleed (watch for unexplained hypotension with back pain). Contrast nephropathy. Stroke (<1%). Coronary dissection/perforation during intervention. Arrhythmias during right heart cath. Contrast allergy. Radial artery occlusion with radial access.'},
{c:'clinical',r:'fellow',q:'When do you use Impella before high-risk PCI?',a:'Severely depressed EF (<30%), unprotected left main, last remaining vessel, complex multivessel with hemodynamic compromise. PROTECT III data supports it. SCAI shock class C or worse \u2014 I want support before starting. Don\u2019t wait until they crash. Place Impella first, stabilize, then intervene.'},
{c:'clinical',r:'resident',q:'How do you anticoagulate a patient with afib and a mechanical valve?',a:'Warfarin only. Never DOACs \u2014 RE-ALIGN trial was stopped for excess events. Target INR: aortic mechanical 2.5, mitral mechanical 3.0. Add aspirin 81mg if additional risk factors. This is a boards question and a real patient safety issue.'},
{c:'clinical',r:'student',q:'How do you differentiate systolic murmurs?',a:'Aortic stenosis: crescendo-decrescendo, right upper sternal border, radiates to carotids. Mitral regurgitation: holosystolic at apex, radiates to axilla. Tricuspid regurgitation: holosystolic, left lower sternal border, increases with inspiration. Valsalva decreases most murmurs but increases HCM and MVP.'},
{c:'clinical',r:'fellow',q:'How has your approach to bifurcation PCI evolved?',a:'More conservative with the side branch over time. Provisional stenting is my default. Only stent side branch if >75% ostial stenosis with TIMI <3 flow. When I need two stents, I prefer DK-crush based on DKCRUSH trials. POT-SIT-POT is critical regardless. Simpler is usually better.'},
{c:'clinical',r:'resident',q:'How do you manage hypertensive emergency vs urgency?',a:'Emergency: end-organ damage present. ICU with IV antihypertensives. Reduce MAP 25% in first hour, then gradually to 160/100 over 24h. Aortic dissection exception: SBP <120, HR <60 fast with esmolol + nicardipine. Urgency: no end-organ damage. Adjust oral meds, follow up 24-48h.'},
{c:'clinical',r:'student',q:'What is the physiology behind S3 and S4 heart sounds?',a:'S3: rapid passive ventricular filling against a dilated ventricle. Normal in young, pathologic in older adults (volume overload). S4: atrial contraction against stiff ventricle. Think LVH, HFpEF. Never normal in adults. Absent in afib. Both heard with bell at apex in left lateral decubitus.'},
{c:'clinical',r:'fellow',q:'What\u2019s your femoral access technique?',a:'Fluoroscopy-guided for every case. Common femoral artery over inferior femoral head border. Micropuncture technique. Pre-close with ProGlide for large bore. Two ProGlides at 10 and 2 o\u2019clock for Impella/large sheaths. Access is the most important part \u2014 bad access turns easy cases into disasters.'},
{c:'clinical',r:'resident',q:'When should I suspect myocarditis?',a:'Young patient with chest pain, new HF, or arrhythmias after viral illness. Troponin elevated, ST changes not in coronary distribution. Workup: ECG, troponin, BNP, echo, cardiac MRI (gold standard). Most viral myocarditis resolves with supportive care. Avoid exercise 3-6 months.'},
{c:'clinical',r:'student',q:'How do you interpret a right heart catheterization?',a:'Key numbers: RA mean (normal <7), RV (25/5), PA (25/10, mean <20), PCWP (<15). Elevated PCWP = left heart failure. Elevated PA with normal PCWP = pulmonary arterial hypertension. Cardiac output by thermodilution or Fick. PVR = (mean PA - PCWP) / CO. This is fundamental to cardiology \u2014 know these numbers cold.'},
{c:'clinical',r:'fellow',q:'When do you consider rotational atherectomy vs orbital atherectomy?',a:'Both for heavily calcified lesions. Rotational atherectomy (Rotablator): more experience, better for ostial calcification, requires dedicated system. Orbital atherectomy (Diamondback): easier to use, treats eccentric calcium well, can orbit at different speeds for different effects. I use rota more for concentric calcification and orbital for eccentric. The key is adequate lesion prep before stenting \u2014 calcium scoring on IVUS/OCT helps decide.'},
{c:'clinical',r:'resident',q:'How do you manage cardiogenic shock?',a:'Identify and treat the cause (MI, myocarditis, PE, arrhythmia). Hemodynamic assessment with PA catheter. Start vasopressors (norepinephrine first per SOAP II trial). Consider inotropes. Evaluate for mechanical circulatory support early \u2014 don\u2019t wait. SCAI shock classification guides escalation. Multidisciplinary shock team approach. Door-to-support time matters as much as door-to-balloon.'},
{c:'clinical',r:'student',q:'What are the classic ECG findings of hyperkalemia?',a:'Progressive with rising K+: peaked T waves (earliest) \u2192 PR prolongation \u2192 QRS widening \u2192 loss of P waves \u2192 sine wave pattern \u2192 asystole. At K+ >6.5, give IV calcium gluconate immediately (cardioprotective, does not lower K+). Then insulin/glucose, kayexalate, and dialysis if needed. This is an emergency you must recognize instantly.'},

// === FINANCE (40) ===
{c:'finance',r:'fellow',q:'Should I refinance student loans during fellowship?',a:'No. Stay on income-driven repayment. Your payments are low. If you refinance, you lose IDR, PSLF, and forbearance protections. Decide after fellowship: academic/non-profit \u2192 PSLF. Private practice \u2192 refinance and pay aggressively. Don\u2019t refinance during training.'},
{c:'finance',r:'resident',q:'What percentage of my attending salary should I save?',a:'20% minimum, aim for 30-40% in your first 3-5 years. You\u2019re used to living on $60-70K. Keep that lifestyle while your income jumps. The difference goes to: maxing retirement, aggressive loan payoff, emergency fund. Lifestyle creep is the #1 wealth destroyer for new attendings.'},
{c:'finance',r:'fellow',q:'Roth IRA vs Traditional IRA during fellowship?',a:'Roth IRA, hands down. Your tax bracket as a fellow is 22-24%. As an attending, 35-37%. Pay taxes now while the rate is low. Max it out ($7,000/year). If income is too high, use backdoor Roth. Single best financial move a trainee can make.'},
{c:'finance',r:'student',q:'How much student debt is too much for cardiology?',a:'With IC salaries of $500-700K+, even $400-500K in debt is manageable if you\u2019re disciplined. Income-driven repayment during training, aggressive payoff as attending. Don\u2019t let debt scare you away from the specialty \u2014 just have a plan.'},
{c:'finance',r:'resident',q:'Do I need disability insurance during residency?',a:'Yes. Buy it now while you\u2019re young and healthy. Get own-occupation policy \u2014 pays if you can\u2019t do YOUR job. Guardian, MassMutual, Principal offer the best physician policies. Residency discounts available. Your earning ability is your biggest asset \u2014 protect it.'},
{c:'finance',r:'fellow',q:'Should I buy a house during fellowship?',a:'Wait. Fellowship is 1-3 years. Transaction costs eat equity. You don\u2019t know where you\u2019ll end up. Rent and save for a down payment. Renting is not throwing money away \u2014 it\u2019s buying flexibility.'},
{c:'finance',r:'resident',q:'What should I do with my first attending paycheck?',a:'In order: 1) Emergency fund (3-6 months). 2) Max retirement accounts (401k, backdoor Roth, HSA). 3) Aggressive loan payoff or PSLF verification. 4) Disability and term life insurance. 5) THEN lifestyle upgrades. Don\u2019t buy house, car, and vacations all at once. First year sets the trajectory.'},
{c:'finance',r:'fellow',q:'What\u2019s a fair signing bonus for a new interventional cardiologist?',a:'$25-100K depending on location and practice type. Academic: $25-50K. Hospital-employed in desirable areas: $50-75K. Rural: $75-100K+. Don\u2019t let the signing bonus distract from total compensation. Look at total comp over 3-5 years, not upfront cash.'},
{c:'finance',r:'student',q:'Should I invest during medical school?',a:'No. That money is borrowed at 6-8%. Investing while paying 6-8% on debt is gambling. Keep a 3-month emergency fund in high-yield savings. Every dollar you don\u2019t borrow is a dollar you don\u2019t pay interest on for 10-15 years.'},
{c:'finance',r:'resident',q:'What tax deductions should physicians know about?',a:'Student loan interest (up to $2,500). CME expenses. License fees. Professional dues. 401k/403b contributions. HSA contributions (triple tax-advantaged). If moonlighting as contractor, many more deductions available. Get a CPA who specializes in physicians \u2014 they pay for themselves.'},
{c:'finance',r:'fellow',q:'How do I negotiate my first attending contract?',a:'Three rules: 1) Never accept the first offer. 2) Get a physician contract attorney ($2-3K). 3) Know the market (MGMA data). Negotiate: base salary, RVU rate, signing bonus, call schedule, partnership track, restrictive covenant, tail coverage. Everything is negotiable. They expect you to negotiate.'},
{c:'finance',r:'resident',q:'Is whole life insurance a good idea for doctors?',a:'Almost never. What you need: term life insurance (20-30 year, 10-15x income if you have dependents). It\u2019s 90% cheaper than whole life. Invest the difference in index funds. Only exception might be estate planning for very high net worth individuals. For 99% of physicians, term is the answer.'},
{c:'finance',r:'fellow',q:'Academic vs private practice \u2014 what\u2019s the real income difference?',a:'In IC, academic salary typically $400-550K. Private practice/hospital-employed $550-800K+. Academic offers: research time, teaching, prestige, PSLF eligibility, slower pace. Private offers: higher income, more autonomy, but more volume pressure. The gap has been narrowing as academic centers try to retain proceduralists. Factor in PSLF \u2014 if you have $300K in loans, PSLF could be worth $200K+ in tax-free forgiveness.'},
{c:'finance',r:'student',q:'What\u2019s the best bank account for medical students?',a:'High-yield savings account for your emergency fund (Ally, Marcus, Discover \u2014 around 4-5% APY). Free checking with no minimum balance. Avoid big bank fees. You don\u2019t need anything fancy. The most important financial move in med school is minimizing how much you borrow, not optimizing your bank account.'},
{c:'finance',r:'resident',q:'Should I moonlight during residency?',a:'If your program allows it and it doesn\u2019t affect your training, yes. The extra income can go to Roth IRA, disability insurance premiums, or emergency savings. But don\u2019t moonlight so much that you burn out or your evaluations suffer. Your career trajectory is worth more than the moonlighting income.'},
{c:'finance',r:'fellow',q:'What should I know about restrictive covenants in physician contracts?',a:'Most contracts have non-compete clauses. Negotiate: shorter duration (1 year max), smaller geographic radius (15-25 miles), carve-outs for academic/VA work, and clear definitions of \u201ccompeting.\u201d Some states don\u2019t enforce non-competes (California). Your attorney should focus on this clause \u2014 it can limit your career more than any other contract term.'},
{c:'finance',r:'student',q:'Is it worth doing MD/MBA?',a:'Only if you want hospital administration, healthcare consulting, or medical device industry. For clinical practice, an MBA won\u2019t significantly increase your income. The opportunity cost (extra 1-2 years of training vs attending salary) is $500K-1M+. Do it for the right reasons, not as a resume line.'},
{c:'finance',r:'resident',q:'How do I start investing as a resident?',a:'Start with Roth IRA (max it out). If your program has a 403b with match, contribute enough to get the full match (free money). After that, taxable brokerage account with low-cost index funds (Vanguard VTSAX, Fidelity FSKAX). Don\u2019t try to pick stocks. Keep it simple. Automate contributions. Time in market beats timing the market.'},
{c:'finance',r:'fellow',q:'What\u2019s tail coverage and why does it matter?',a:'Tail coverage pays for malpractice claims filed after you leave a practice, for events that occurred while you were there. It\u2019s typically 2-3x your annual malpractice premium ($20-50K for IC). Negotiate for your employer to pay it. If they won\u2019t, get it in writing that you\u2019re responsible and budget for it. Leaving without tail coverage exposes you to significant liability.'},
{c:'finance',r:'resident',q:'How do you handle student loans and planning a wedding during residency?',a:'Be honest with your partner about debt. Set a realistic wedding budget \u2014 don\u2019t borrow for it. Remember your attending income is coming. Keep wedding spending separate from loan strategy. Stay on IDR for loans. Use savings for the wedding, not borrowed money. Financial transparency early in a relationship prevents bigger problems later.'},

// === CAREER (40) ===
{c:'career',r:'student',q:'How competitive is interventional cardiology fellowship?',a:'Very competitive. Typical successful applicants have: strong letters from cardiology attendings, 2-3+ first-author publications, presentations at ACC/AHA, excellent fellowship training, and genuine procedural enthusiasm. It\u2019s not just metrics though \u2014 programs want people who will be excellent operators and team members.'},
{c:'career',r:'resident',q:'How many programs should I apply to for cardiology fellowship?',a:'25-40 programs is typical. Apply broadly, especially if you\u2019re at a community program or have a less competitive application. If you\u2019re at a top academic center with strong letters and publications, 20-25 may suffice. Better to over-apply than under-apply.'},
{c:'career',r:'fellow',q:'What\u2019s the job market like for new interventional cardiologists?',a:'Excellent. IC is in high demand. Most fellows have multiple offers before graduation. The shortage is especially acute in non-coastal areas. You\u2019ll have leverage in negotiation. Hospital-employed positions are most common, but private practice opportunities exist. Structural heart skills (TAVR) make you even more marketable.'},
{c:'career',r:'student',q:'Do I need to go to a top residency program to match into cardiology?',a:'No. Many excellent cardiologists trained at community programs. What matters: strong performance on rotations, good letters from cardiologists who know you, research productivity, and board scores. A strong applicant from a community program beats a mediocre applicant from a brand-name program every time.'},
{c:'career',r:'resident',q:'How do I get strong letters of recommendation for fellowship?',a:'Work with your letter writers on clinical rotations \u2014 not just research. They need to speak to your clinical skills, work ethic, and personality. Ask early (6+ months before applications). Choose writers who are known in cardiology and can write detailed, personal letters. A lukewarm letter from a famous person is worse than a strong letter from someone less known.'},
{c:'career',r:'fellow',q:'Should I do a structural heart fellowship after IC?',a:'If you\u2019re interested in TAVR, MitraClip, WATCHMAN, and other structural interventions, yes. It\u2019s an extra year but makes you significantly more marketable. The field is exploding. In 5-10 years, structural heart skills may be expected for IC attendings. Not everyone needs it, but if you love it, it\u2019s a great investment.'},
{c:'career',r:'student',q:'What kind of research impresses cardiology fellowship programs most?',a:'First-author clinical publications in cardiology journals (JACC, Circulation, Heart). Presentations at ACC or AHA. Meaningful involvement \u2014 not just name on a paper. Programs can tell the difference between someone who did the work and someone who just collected data. One thoughtful first-author paper > five middle-author papers.'},
{c:'career',r:'resident',q:'Is it better to do cardiology fellowship at the same institution as residency?',a:'There\u2019s no penalty for staying. If your program has a strong cardiology division and you\u2019re competitive, it can actually help \u2014 they know you, you know the system. But if the program is weak in cardiology or you want different training, absolutely look elsewhere. Match where you\u2019ll get the best training.'},
{c:'career',r:'fellow',q:'How do I evaluate whether a practice is a good fit during the job search?',a:'Visit for at least a full day. Scrub cases with the IC team. Talk to the junior partners separately from senior partners. Ask about: call schedule, volume trends, relationship with hospital administration, support staff quality, equipment/technology, and the unspoken culture. Talk to the recently hired attendings \u2014 were promises kept?'},
{c:'career',r:'student',q:'What makes a good personal statement for residency if I\u2019m interested in cardiology?',a:'Don\u2019t write about cardiology specifically in your IM residency personal statement. Write about why you love internal medicine. Mention an experience that shows curiosity, dedication, and empathy. Program directors are selecting residents, not cardiologists. If you\u2019re too narrowly focused on cardiology, some programs worry you won\u2019t engage with non-cardiology rotations.'},
{c:'career',r:'resident',q:'When should I start networking for fellowship applications?',a:'PGY-2, ideally the fall. Attend ACC or AHA if possible. Reach out to fellows at programs you like and ask about their experience. Introduce yourself to visiting speakers. Your PD\u2019s connections matter \u2014 ask them to make introductions. Networking isn\u2019t schmoozing, it\u2019s building genuine professional relationships.'},
{c:'career',r:'fellow',q:'Is it worth doing a year as a cardiology hospitalist before IC fellowship?',a:'It can help if you need more clinical experience or research time. Some people use the gap year to bolster their IC application. But it\u2019s not necessary if you\u2019re competitive. If you\u2019re matched at a strong program already, go straight to IC fellowship. Don\u2019t delay if you don\u2019t need to.'},
{c:'career',r:'student',q:'How important are board scores for cardiology fellowship?',a:'Step 1 is now pass/fail so it matters less. Step 2 CK score still matters \u2014 aim for 250+. ITE scores matter. But scores are just one factor. Programs weight clinical evaluations, letters, and research heavily too. A great clinical reputation can compensate for average scores, but not vice versa.'},
{c:'career',r:'resident',q:'Should I do an IM chief year before applying to cardiology?',a:'It can strengthen your application \u2014 shows leadership, commitment, maturity. Many successful cardiology fellows did chief year. But it adds a year to your training timeline. If your application is already strong, you don\u2019t need it. If you\u2019re borderline, it can be the differentiator. I did it and it helped me tremendously.'},
{c:'career',r:'fellow',q:'How do I build a clinical niche as a new attending?',a:'Pick 1-2 areas of expertise and become the go-to person. CTO PCI, structural heart, peripheral interventions, cardiogenic shock \u2014 whatever you\u2019re passionate about. Attend specialized conferences, get extra training, publish in that area. Your referral base grows when other doctors know you for something specific.'},
{c:'career',r:'student',q:'What lifestyle can I expect as an interventional cardiologist?',a:'Honest answer: it\u2019s demanding. You take STEMI call (middle-of-the-night cases). Weekday schedule is clinic + cath lab + consults. Typical week is 50-60 hours when not on call. On call weekends vary by group (1:3 to 1:6). But the work is incredibly rewarding \u2014 you save lives in real-time. Compensation is among the highest in medicine. Work-life balance is achievable in the right practice.'},
{c:'career',r:'resident',q:'How do I handle rejection from fellowship programs?',a:'It happens. Even strong applicants get rejected. Don\u2019t take it personally \u2014 programs have idiosyncratic preferences. If you don\u2019t match, regroup: talk to your PD, identify weaknesses, strengthen your application. Many excellent cardiologists matched on their second attempt. The year in between is often used productively for research and clinical experience. Persistence matters more than perfection.'},
{c:'career',r:'fellow',q:'What\u2019s the difference between working for a hospital system vs private group?',a:'Hospital-employed: guaranteed salary, less business risk, benefits package, but less autonomy and income ceiling. Private group: higher earning potential, more autonomy, but you share in business risk, overhead, and partner dynamics. Hospital employment is increasingly common. The ideal depends on your risk tolerance and whether you want to focus purely on medicine or also run a business.'},
{c:'career',r:'student',q:'Can international medical graduates (IMGs) become interventional cardiologists?',a:'Absolutely. I\u2019ve worked with excellent IC attendings who are IMGs. The path is harder \u2014 you need to match IM residency first (often at community programs), then prove yourself for cardiology fellowship. Strong board scores, research, and letters are essential. It takes more intentional effort, but it\u2019s very achievable.'},
{c:'career',r:'resident',q:'How do you manage work-life balance during fellowship?',a:'Honestly, fellowship isn\u2019t balanced. It\u2019s intense. But you can be intentional: protect one evening per week for family/friends, exercise regularly (even 30 minutes makes a difference), set boundaries on non-essential tasks, and communicate with your partner about expectations. It\u2019s a temporary sacrifice for a career you\u2019ll love. But if you\u2019re burning out, talk to someone \u2014 that\u2019s not weakness, it\u2019s wisdom.'},
{c:'career',r:'fellow',q:'Should I join a practice with partners or start solo?',a:'Join an established group. Starting solo as an IC is extremely difficult \u2014 you need cath lab privileges, hospital relationships, referral networks, and support staff. It takes years to build volume. Joining a group gives you instant infrastructure, mentorship from senior partners, and shared call. You can always transition later once you\u2019re established.'},
{c:'career',r:'student',q:'What\u2019s the match rate for cardiology fellowship?',a:'Around 70-75% of applicants match. It\u2019s competitive but not impossible. The key is realistic expectations about which tier of program you\u2019re competitive for, and applying broadly enough. Programs have expanded spots in recent years due to demand. If you\u2019re a solid applicant with good letters, research, and clinical skills, your chances are good.'},
{c:'career',r:'resident',q:'How important is the program\u2019s cath lab volume for IC fellowship training?',a:'Very important. You want a program where you\u2019ll get at least 250+ interventional cases in your year. Higher volume means more complex cases, more variety, and better procedural skills. Ask for the fellow case log numbers. Also look at the case mix \u2014 do they do CTOs, peripheral, structural? Volume + variety is the ideal combination.'},

// === WELLNESS (40) ===
{c:'wellness',r:'resident',q:'How do you deal with burnout during fellowship?',a:'First, acknowledge it. You\u2019re not weak for feeling burned out. The hours are real and the pressure is immense. What helped me: exercise (even short walks), maintaining one non-medicine interest, talking to co-fellows (they\u2019re feeling it too), and remembering this is temporary. If it\u2019s severe, use your program\u2019s mental health resources. Your future patients need you healthy.'},
{c:'wellness',r:'student',q:'How do you maintain relationships during medical school?',a:'Communication and realistic expectations. Your partner/friends need to understand that your schedule is unpredictable. Protect quality time \u2014 even 30 minutes of focused attention is better than hours of distracted presence. Be honest about your limitations. The people who stick around during training are your people for life.'},
{c:'wellness',r:'fellow',q:'How do you handle the stress of a bad outcome in the cath lab?',a:'Every interventional cardiologist has had complications. The first one is devastating. What helps: debrief with your attending immediately, review what happened objectively (was it preventable? what would you do differently?), talk to a senior colleague who\u2019s been through it. Don\u2019t self-isolate. M&M conferences exist for a reason. The worst thing you can do is pretend you\u2019re fine when you\u2019re not.'},
{c:'wellness',r:'resident',q:'I\u2019m an IM resident and I\u2019m not sure if I want to do cardiology anymore. Is that normal?',a:'Completely normal. Training fatigue can make you question everything. Take a step back \u2014 is it the specialty or the training environment? Shadow in a cardiology practice (not the hospital) to see what attending life actually looks like. Many residents feel this way in PGY-2/3 and go on to love cardiology. But if you genuinely lost interest, that\u2019s okay too. Better to know now.'},
{c:'wellness',r:'student',q:'How do you not feel overwhelmed by how much there is to learn in cardiology?',a:'You\u2019re not supposed to know everything. Even attendings are constantly learning. Focus on the fundamentals first: heart failure, ACS, arrhythmias, valvular disease. Master those. Everything else builds on that foundation. Learn a little every day. In a year, you\u2019ll be amazed at how much you know. Compare yourself to yourself, not to the person next to you.'},
{c:'wellness',r:'fellow',q:'How do you manage call nights without destroying your sleep schedule?',a:'On call: sleep when you can, caffeine strategically (not after midnight), and have a system for triaging consults quickly. Post-call: go home immediately, darken your room, nap for 4-5 hours (not 8, or you\u2019ll wreck the next night). Then get sunlight and exercise in the afternoon. Back to normal bedtime that night. Consistency matters more than perfection.'},
{c:'wellness',r:'resident',q:'My co-residents seem more prepared than me. Am I falling behind?',a:'Imposter syndrome is rampant in medicine. They\u2019re probably thinking the same thing about you. Focus on your own growth trajectory. If you\u2019re improving month over month, you\u2019re on track. Ask for specific feedback from attendings \u2014 don\u2019t rely on your own anxious self-assessment. You matched for a reason.'},
{c:'wellness',r:'student',q:'Is it okay to have a life outside of medicine?',a:'Not just okay \u2014 essential. The best physicians I know have rich lives outside the hospital. Hobbies, relationships, travel, interests. It makes you more empathetic, more resilient, and frankly more interesting. Medicine will consume you if you let it. Don\u2019t let it. You\u2019re a person first, a doctor second.'},
{c:'wellness',r:'fellow',q:'How do you decompress after a long week in the cath lab?',a:'I exercise \u2014 it\u2019s non-negotiable for me. Also: time with family where I\u2019m fully present (phone away), cooking (meditative and you eat well), and occasionally doing absolutely nothing productive. The worst thing is scrolling work emails all weekend. You need mental separation from the hospital or you\u2019ll burn out.'},
{c:'wellness',r:'resident',q:'How do you handle difficult attendings during training?',a:'Document everything professionally. Stay calm and objective. Don\u2019t gossip \u2014 it always gets back to them. If it\u2019s truly malignant behavior, report it to your PD. For garden-variety difficult personalities: learn what they want and deliver it efficiently. Some of the hardest attendings teach you the most. But abuse is never acceptable.'},
{c:'wellness',r:'student',q:'I\u2019m drowning in debt and it\u2019s affecting my mental health. Any advice?',a:'Your debt feels crushing now, but remember: you\u2019re investing in one of the highest-earning careers that exists. A cardiology attending earns enough to eliminate even $500K in debt within 5-7 years. Right now, focus on your training. Use income-driven repayment so payments are manageable. Talk to a financial advisor (many offer free initial consultations for trainees). And if the anxiety is severe, your school has counseling resources. Use them.'},
{c:'wellness',r:'fellow',q:'How do you maintain your marriage or relationship during IC fellowship?',a:'Intentional effort. My spouse and I had a weekly date night that was sacred \u2014 even if it was just dinner at home. Communicate about call schedules in advance. Acknowledge that you\u2019re going to miss things. Express gratitude often. IC fellowship is particularly hard because of STEMI call unpredictability. Your partner needs to understand what they\u2019re signing up for. Consider couples counseling proactively, not reactively.'},
{c:'wellness',r:'resident',q:'Do you regret going into interventional cardiology?',a:'Not for a second. The training was brutal. The call is demanding. But I get to save lives in real-time. I open blocked arteries and see immediate results. I counsel patients through the scariest moment of their lives. The financial security is excellent. And the intellectual challenge never ends. Would I do it again? Absolutely. The sacrifice is real, but so is the reward.'},
{c:'wellness',r:'student',q:'How do you deal with watching patients die?',a:'It never gets easy, and if it does, something\u2019s wrong. What changes is your ability to process it. Early on, every death hits hard. Over time, you learn to compartmentalize during the moment and process it later. Talk to colleagues. Reflect on what you did right, not just what you lost. Some deaths are preventable and those require honest review. Most are not, and accepting that is part of becoming a physician.'},
{c:'wellness',r:'fellow',q:'I\u2019m a female fellow in IC and sometimes feel like I don\u2019t belong. How do you address gender bias?',a:'First: you absolutely belong. IC needs more women and the field is better for it. The bias is real \u2014 I\u2019ve seen it. Combat it by being excellent at what you do, finding female mentors in IC (they exist and are growing in number), connecting with WIC (Women in Interventional Cardiology) through SCAI, and not accepting behavior that wouldn\u2019t be directed at a male fellow. Speak up. And know that you\u2019re paving the way for the next generation.'},
{c:'wellness',r:'resident',q:'How do I know if I need professional help for my mental health?',a:'If you\u2019re asking this question, it\u2019s worth exploring. Signs: persistent sadness, inability to enjoy things you used to, changes in sleep/appetite, difficulty concentrating, feelings of hopelessness, increased substance use, thoughts of self-harm. You don\u2019t need to be in crisis to seek help. Many physicians benefit from therapy during training. It\u2019s not weakness \u2014 it\u2019s self-awareness. Most state medical boards do not ask about voluntary mental health treatment.'},
{c:'wellness',r:'student',q:'How do you stay physically healthy during medical school?',a:'Schedule exercise like you schedule studying \u2014 it\u2019s non-negotiable. Even 20-30 minutes, 4x/week makes a dramatic difference. Meal prep on Sundays. Sleep 7 hours minimum (your retention improves). Limit caffeine after 2pm. Take breaks during study sessions. Your body is the vehicle for your career \u2014 treat it like one.'},
{c:'wellness',r:'fellow',q:'What do you wish you knew about work-life balance before becoming an attending?',a:'That it doesn\u2019t magically get better when you finish training. You have to actively create boundaries. Set your clinic schedule intentionally. Don\u2019t say yes to every committee. Protect your weekends off. Hire help at home if you can afford it (you can as an attending). The attendings who burn out are the ones who never learned to say no. Start practicing now.'},
{c:'wellness',r:'resident',q:'How do you cope with making a medical error?',a:'Disclose it (ethically required and practically important). Debrief with your team. Report it through your institution\u2019s safety system. Reflect on what happened and what you\u2019d do differently. Don\u2019t ruminate alone \u2014 talk to a trusted colleague or mentor. Every physician makes errors. What defines you is how you respond: honestly, humbly, and with a commitment to learning.'},
{c:'wellness',r:'student',q:'Is it normal to feel like I chose the wrong career in medicine?',a:'Yes \u2014 almost every medical student and resident has this thought at some point. It usually happens during the hardest rotations or when you\u2019re sleep-deprived. It\u2019s rarely about the career itself and more about the temporary misery of training. Talk to attendings who love their work \u2014 their perspective helps. If the feeling persists beyond a bad rotation, explore it honestly. But don\u2019t make permanent decisions based on temporary feelings.'}
];

// Date generator: random dates in last 6 months
function randDate(){const d=new Date();d.setDate(d.getDate()-Math.floor(Math.random()*180));return d.toISOString().split('T')[0]}

// Build questions array
const questions = QA.map((q,i)=>{
    const users = SEED_USERS.filter(u=>u.role===q.r);
    const user = users[i % users.length];
    const isAnon = user.name === 'Anonymous';
    return {
        id: i+100,
        userId: user.id,
        author: isAnon ? 'Anonymous' : user.name,
        role: q.r,
        category: q.c,
        question: q.q,
        anonymous: isAnon,
        date: randDate(),
        status: 'answered',
        answer: q.a
    };
});

// Sort by date
questions.sort((a,b)=>a.date.localeCompare(b.date));

// Output as JSON
console.log(JSON.stringify({questions, count: questions.length}));
